<?php if ($is_new): ?>
<h1><?php echo $this->translate('Galerie_add_title', 'galerie'); ?></h1>
<?php else: ?>
<h1><?php echo $this->translate('Galerie_edit_title', 'galerie'); ?></h1>
<?php endif; ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<div style="overflow: hidden; width: 100%;">
    <span style="float: left; width: 150px; text-align: right; font-weight: bold; cursor: pointer;">
        <?php echo $this->formLabel($form->get('name')); ?>
    </span>
    <span style="width: 250px; margin-left: 12px;">
        <?php echo $this->formText($form->get('name')); ?>
    </span>
</div>
<div style="overflow: hidden; width: 100%;">
    <span style="float: left; width: 150px; text-align: right; font-weight: bold; cursor: pointer;">
        <?php echo $this->formLabel($form->get('description')); ?>
    </span>
    <span style="width: 250px; margin-left: 12px;">
        <?php echo $this->formText($form->get('description')); ?>
    </span>
</div>
<div style="overflow: hidden; width: 100%;">
    <span style="width: 250px; margin-left: 162px;">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </span>
</div>
<?php echo $this->form()->closeTag($form); ?>
